# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-08-20 18:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('colony', '0003_auto_20160818_1807'),
    ]

    operations = [
        migrations.CreateModel(
            name='MouseMove',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('move_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('from_cage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='colony.Cage')),
                ('mouse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='colony.Mouse')),
            ],
        ),
    ]
