# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-08-20 21:18
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('colony', '0005_historicalcage_historicalgenotype_historicallitter_historicalperson_historicalspecialrequest'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='assigned_to',
        ),
        migrations.RemoveField(
            model_name='task',
            name='cages',
        ),
        migrations.RemoveField(
            model_name='task',
            name='created_by',
        ),
        migrations.DeleteModel(
            name='Task',
        ),
    ]
