# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-08-20 23:40
from __future__ import unicode_literals

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('colony', '0006_auto_20160820_1718'),
    ]

    operations = [
        migrations.AddField(
            model_name='cage',
            name='tgeno',
            field=autoslug.fields.AutoSlugField(default='autoslug', editable=False, populate_from=('litter__mother__genotype__name', 'litter__father__genotype__name')),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='historicalcage',
            name='tgeno',
            field=autoslug.fields.AutoSlugField(default='autoslug', editable=False, populate_from=('litter__mother__genotype__name', 'litter__father__genotype__name')),
            preserve_default=False,
        ),
    ]
