# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-12-11 21:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('colony', '0007_auto_20160820_2108'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gene',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('gene_type', models.CharField(blank=True, choices=[('reporter', 'reporter'), ('driver', 'driver')], max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='MouseGene',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zygosity', models.CharField(choices=[('+/+', '+/+'), ('+/-', '+/-'), ('+/?', '+/?'), ('?/-', '?/-'), ('?/?', '?/?'), ('-/-', '-/-')], max_length=10)),
                ('gene_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='colony.Gene')),
            ],
        ),
        migrations.AddField(
            model_name='historicalmouse',
            name='pure_breeder',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='historicalmouse',
            name='wild_type',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='mouse',
            name='pure_breeder',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='mouse',
            name='wild_type',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='mousegene',
            name='mouse_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='colony.Mouse'),
        ),
    ]
