# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-08-20 23:46
from __future__ import unicode_literals

import autoslug.fields
import colony.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('colony', '0008_auto_20160820_1943'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cage',
            name='tgeno',
            field=autoslug.fields.AutoSlugField(always_update=True, editable=False, populate_from=colony.models.get_tgeno),
        ),
        migrations.AlterField(
            model_name='historicalcage',
            name='tgeno',
            field=autoslug.fields.AutoSlugField(always_update=True, editable=False, populate_from=colony.models.get_tgeno),
        ),
    ]
