# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-12-18 23:36
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('colony', '0008_auto_20161211_1642'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mousegene',
            options={'ordering': ('gene_name__gene_type', 'gene_name__name')},
        ),
    ]
