# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-12-29 21:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('colony', '0009_auto_20161218_1836'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='gene',
            options={'ordering': ['gene_type', 'name']},
        ),
        migrations.AlterField(
            model_name='historicalmouse',
            name='pure_breeder',
            field=models.BooleanField(default=False, help_text='Check this box if this mouse was acquired as a pure breeder. Its progeny with a wild type will automatically inherit this status.'),
        ),
        migrations.AlterField(
            model_name='historicalmouse',
            name='wild_type',
            field=models.BooleanField(default=False, help_text='Check this box if this mouse was acquired as a pure wild type.'),
        ),
        migrations.AlterField(
            model_name='mouse',
            name='pure_breeder',
            field=models.BooleanField(default=False, help_text='Check this box if this mouse was acquired as a pure breeder. Its progeny with a wild type will automatically inherit this status.'),
        ),
        migrations.AlterField(
            model_name='mouse',
            name='wild_type',
            field=models.BooleanField(default=False, help_text='Check this box if this mouse was acquired as a pure wild type.'),
        ),
    ]
