# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-08-21 00:19
from __future__ import unicode_literals

import autoslug.fields
import colony.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('colony', '0010_auto_20160820_1959'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cage',
            name='tgeno',
        ),
        migrations.RemoveField(
            model_name='historicalcage',
            name='tgeno',
        ),
        migrations.AddField(
            model_name='historicallitter',
            name='target_genotype',
            field=autoslug.fields.AutoSlugField(always_update=True, default='autoslug', editable=False, populate_from=colony.models.slug_target_genotype, slugify=colony.models.my_slugify),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='litter',
            name='target_genotype',
            field=autoslug.fields.AutoSlugField(always_update=True, default='autoslug', editable=False, populate_from=colony.models.slug_target_genotype, slugify=colony.models.my_slugify),
            preserve_default=False,
        ),
    ]
