# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-12-29 23:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('colony', '0010_auto_20161229_1621'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mouse',
            name='genotype',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='colony.Genotype'),
        ),
    ]
