# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-01-05 04:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('colony', '0012_auto_20161229_2157'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicallitter',
            name='date_genotyped',
            field=models.DateField(blank=True, null=True, verbose_name='genotyped'),
        ),
        migrations.AddField(
            model_name='litter',
            name='date_genotyped',
            field=models.DateField(blank=True, null=True, verbose_name='genotyped'),
        ),
    ]
