# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-01-26 00:17
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('colony', '0013_auto_20170104_2332'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cage',
            options={'ordering': ['name']},
        ),
    ]
