# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-02-13 16:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('colony', '0014_auto_20170125_1917'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cage',
            name='location',
            field=models.IntegerField(choices=[(0, '1710'), (1, '1702'), (2, 'Behavior'), (3, '1736')], default=0),
        ),
        migrations.AlterField(
            model_name='historicalcage',
            name='location',
            field=models.IntegerField(choices=[(0, '1710'), (1, '1702'), (2, 'Behavior'), (3, '1736')], default=0),
        ),
    ]
