# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2018-01-08 21:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('colony', '0015_auto_20170213_1145'),
    ]

    operations = [
        migrations.AddField(
            model_name='cage',
            name='transfer_JLG',
            field=models.NullBooleanField(default=None),
        ),
        migrations.AddField(
            model_name='historicalcage',
            name='transfer_JLG',
            field=models.NullBooleanField(default=None),
        ),
    ]
