# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2018-02-20 04:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('colony', '0019_auto_20180219_2336'),
    ]

    operations = [
        migrations.AddField(
            model_name='cage',
            name='rack_spot',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='historicalcage',
            name='rack_spot',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
