# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2018-03-14 20:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('colony', '0020_auto_20180219_2341'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalcage',
            name='history_change_reason',
        ),
        migrations.RemoveField(
            model_name='historicalgenotype',
            name='history_change_reason',
        ),
        migrations.RemoveField(
            model_name='historicallitter',
            name='history_change_reason',
        ),
        migrations.RemoveField(
            model_name='historicalmouse',
            name='history_change_reason',
        ),
        migrations.RemoveField(
            model_name='historicalperson',
            name='history_change_reason',
        ),
        migrations.RemoveField(
            model_name='historicalspecialrequest',
            name='history_change_reason',
        ),
        migrations.AlterField(
            model_name='cage',
            name='location',
            field=models.IntegerField(choices=[(0, '1710'), (1, '1702'), (2, 'Behavior'), (3, '1736'), (4, 'SC2-011'), (5, 'L7-007'), (6, 'SC2-056'), (7, 'SC2-044')], default=4),
        ),
        migrations.AlterField(
            model_name='historicalcage',
            name='location',
            field=models.IntegerField(choices=[(0, '1710'), (1, '1702'), (2, 'Behavior'), (3, '1736'), (4, 'SC2-011'), (5, 'L7-007'), (6, 'SC2-056'), (7, 'SC2-044')], default=4),
        ),
    ]
