# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2018-03-26 22:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('colony', '0021_auto_20180314_1618'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cage',
            name='location',
            field=models.IntegerField(choices=[(0, '1710'), (1, '1702'), (2, 'Behavior'), (3, '1736'), (4, 'SC2-011'), (5, 'L7-057'), (6, 'SC2-056'), (7, 'SC2-044')], default=4),
        ),
        migrations.AlterField(
            model_name='historicalcage',
            name='location',
            field=models.IntegerField(choices=[(0, '1710'), (1, '1702'), (2, 'Behavior'), (3, '1736'), (4, 'SC2-011'), (5, 'L7-057'), (6, 'SC2-056'), (7, 'SC2-044')], default=4),
        ),
    ]
