# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2018-04-15 20:12
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('colony', '0023_auto_20180415_1601'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='person',
            options={'ordering': ['name']},
        ),
    ]
