# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-08-06 23:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('colony', '0025_auto_20180611_1647'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalperson',
            name='login_name',
            field=models.CharField(default='', max_length=15),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='person',
            name='login_name',
            field=models.CharField(default='', max_length=15),
            preserve_default=False,
        ),
    ]
