# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-08-06 23:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('colony', '0027_auto_20180806_1933'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalperson',
            name='login_name',
            field=models.CharField(db_index=True, help_text='manually set this to their login name', max_length=15),
        ),
        migrations.AlterField(
            model_name='person',
            name='login_name',
            field=models.CharField(help_text='manually set this to their login name', max_length=15, unique=True),
        ),
    ]
