# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-08-06 23:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('colony', '0028_auto_20180806_1939'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalperson',
            name='series_number',
            field=models.IntegerField(default=9, help_text='cage series number'),
        ),
        migrations.AddField(
            model_name='person',
            name='series_number',
            field=models.IntegerField(default=9, help_text='cage series number'),
        ),
    ]
