# Generated by Django 3.0.1 on 2019-12-22 16:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('colony', '0031_auto_20180810_1603'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cage',
            name='proprietor',
            field=models.ForeignKey(limit_choices_to={'active': True}, on_delete=django.db.models.deletion.PROTECT, to='colony.Person'),
        ),
        migrations.AlterField(
            model_name='historicalcage',
            name='proprietor',
            field=models.ForeignKey(blank=True, db_constraint=False, limit_choices_to={'active': True}, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='colony.Person'),
        ),
        migrations.AlterField(
            model_name='historicallitter',
            name='father',
            field=models.ForeignKey(blank=True, db_constraint=False, limit_choices_to={'sex': 0}, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='colony.Mouse'),
        ),
        migrations.AlterField(
            model_name='historicallitter',
            name='mother',
            field=models.ForeignKey(blank=True, db_constraint=False, limit_choices_to={'sex': 1}, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='colony.Mouse'),
        ),
        migrations.AlterField(
            model_name='historicalmouse',
            name='user',
            field=models.ForeignKey(blank=True, db_constraint=False, limit_choices_to={'active': True}, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='colony.Person'),
        ),
        migrations.AlterField(
            model_name='historicalspecialrequest',
            name='requestee',
            field=models.ForeignKey(blank=True, db_constraint=False, limit_choices_to={'active': True}, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='colony.Person'),
        ),
        migrations.AlterField(
            model_name='historicalspecialrequest',
            name='requester',
            field=models.ForeignKey(blank=True, db_constraint=False, limit_choices_to={'active': True}, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='colony.Person'),
        ),
        migrations.AlterField(
            model_name='litter',
            name='father',
            field=models.ForeignKey(limit_choices_to={'sex': 0}, on_delete=django.db.models.deletion.PROTECT, related_name='bc_father', to='colony.Mouse'),
        ),
        migrations.AlterField(
            model_name='litter',
            name='mother',
            field=models.ForeignKey(limit_choices_to={'sex': 1}, on_delete=django.db.models.deletion.PROTECT, related_name='bc_mother', to='colony.Mouse'),
        ),
        migrations.AlterField(
            model_name='litter',
            name='proprietor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='colony.Person'),
        ),
        migrations.AlterField(
            model_name='mouse',
            name='cage',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='colony.Cage'),
        ),
        migrations.AlterField(
            model_name='mouse',
            name='genotype',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='colony.Genotype'),
        ),
        migrations.AlterField(
            model_name='mouse',
            name='litter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='colony.Litter'),
        ),
        migrations.AlterField(
            model_name='mouse',
            name='manual_father',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='mmf', to='colony.Mouse'),
        ),
        migrations.AlterField(
            model_name='mouse',
            name='manual_mother',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='mmm', to='colony.Mouse'),
        ),
        migrations.AlterField(
            model_name='mouse',
            name='user',
            field=models.ForeignKey(blank=True, limit_choices_to={'active': True}, null=True, on_delete=django.db.models.deletion.PROTECT, to='colony.Person'),
        ),
        migrations.AlterField(
            model_name='mousegene',
            name='gene_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='colony.Gene'),
        ),
        migrations.AlterField(
            model_name='mousegene',
            name='mouse_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='colony.Mouse'),
        ),
        migrations.AlterField(
            model_name='specialrequest',
            name='cage',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='colony.Cage'),
        ),
        migrations.AlterField(
            model_name='specialrequest',
            name='requestee',
            field=models.ForeignKey(blank=True, limit_choices_to={'active': True}, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='requests_for_me', to='colony.Person'),
        ),
        migrations.AlterField(
            model_name='specialrequest',
            name='requester',
            field=models.ForeignKey(blank=True, limit_choices_to={'active': True}, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='requests_from_me', to='colony.Person'),
        ),
    ]
