# Generated by Django 3.0.1 on 2019-12-27 18:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('colony', '0032_auto_20191222_1142'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mousegene',
            name='mouse_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='colony.Mouse'),
        ),
    ]
