# Generated by Django 4.0.4 on 2022-05-03 02:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('colony', '0034_auto_20220426_2149'),
    ]

    operations = [
        migrations.CreateModel(
            name='Strain',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.RenameField(
            model_name='historicalmouse',
            old_name='wild_type',
            new_name='pure_wild_type',
        ),
        migrations.RenameField(
            model_name='mouse',
            old_name='wild_type',
            new_name='pure_wild_type',
        ),
        migrations.RemoveField(
            model_name='cage',
            name='transfer_JLG',
        ),
        migrations.RemoveField(
            model_name='historicalcage',
            name='transfer_JLG',
        ),
        migrations.RemoveField(
            model_name='historicalmouse',
            name='breeder',
        ),
        migrations.RemoveField(
            model_name='historicalmouse',
            name='genotype',
        ),
        migrations.RemoveField(
            model_name='mouse',
            name='breeder',
        ),
        migrations.RemoveField(
            model_name='mouse',
            name='genotype',
        ),
        migrations.AlterField(
            model_name='cage',
            name='location',
            field=models.IntegerField(choices=[(0, 'L44')], default=0),
        ),
        migrations.AlterField(
            model_name='cage',
            name='name',
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='historicalcage',
            name='location',
            field=models.IntegerField(choices=[(0, 'L44')], default=0),
        ),
        migrations.AlterField(
            model_name='historicalcage',
            name='name',
            field=models.CharField(db_index=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='historicallitter',
            name='notes',
            field=models.CharField(blank=True, default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='historicallitter',
            name='pcr_info',
            field=models.CharField(blank=True, default='', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='historicalmouse',
            name='notes',
            field=models.CharField(blank=True, default='', max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='litter',
            name='notes',
            field=models.CharField(blank=True, default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='litter',
            name='pcr_info',
            field=models.CharField(blank=True, default='', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='mouse',
            name='notes',
            field=models.CharField(blank=True, default='', max_length=200),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='MouseStrain',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight', models.FloatField(default=1.0, help_text='the relative weight of this strain in this mouse')),
                ('mouse_key', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='colony.mouse')),
                ('strain_key', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='colony.strain')),
            ],
        ),
    ]
