# Generated by Django 4.0.4 on 2022-05-04 01:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('colony', '0038_alter_cage_dar_id_alter_cage_dar_req_num_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cage',
            name='dar_type',
            field=models.IntegerField(choices=[(0, 'unknown (must specify)'), (1, 'separation'), (2, 'weaning'), (3, 'ordered/imported')], default=0, help_text='where the cage came from, and what kind of card it has', verbose_name='DAR type'),
        ),
        migrations.AlterField(
            model_name='cage',
            name='defunct',
            field=models.BooleanField(default=False, help_text='set True when the cage no longer physically exists'),
        ),
        migrations.AlterField(
            model_name='cage',
            name='location',
            field=models.IntegerField(choices=[(0, 'L44')], default=0, help_text='where the cage is physically located'),
        ),
        migrations.AlterField(
            model_name='cage',
            name='name',
            field=models.CharField(help_text='a unique name for this cage', max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='cage',
            name='notes',
            field=models.CharField(blank=True, help_text='any custom notes about this cage', max_length=100),
        ),
        migrations.AlterField(
            model_name='cage',
            name='proprietor',
            field=models.ForeignKey(help_text='the person responsible for the cage', limit_choices_to={'active': True}, on_delete=django.db.models.deletion.PROTECT, to='colony.person'),
        ),
        migrations.AlterField(
            model_name='historicalcage',
            name='dar_type',
            field=models.IntegerField(choices=[(0, 'unknown (must specify)'), (1, 'separation'), (2, 'weaning'), (3, 'ordered/imported')], default=0, help_text='where the cage came from, and what kind of card it has', verbose_name='DAR type'),
        ),
        migrations.AlterField(
            model_name='historicalcage',
            name='defunct',
            field=models.BooleanField(default=False, help_text='set True when the cage no longer physically exists'),
        ),
        migrations.AlterField(
            model_name='historicalcage',
            name='location',
            field=models.IntegerField(choices=[(0, 'L44')], default=0, help_text='where the cage is physically located'),
        ),
        migrations.AlterField(
            model_name='historicalcage',
            name='name',
            field=models.CharField(db_index=True, help_text='a unique name for this cage', max_length=50),
        ),
        migrations.AlterField(
            model_name='historicalcage',
            name='notes',
            field=models.CharField(blank=True, help_text='any custom notes about this cage', max_length=100),
        ),
        migrations.AlterField(
            model_name='historicalcage',
            name='proprietor',
            field=models.ForeignKey(blank=True, db_constraint=False, help_text='the person responsible for the cage', limit_choices_to={'active': True}, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='colony.person'),
        ),
    ]
