# Generated by Django 4.0.4 on 2022-05-04 01:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('colony', '0040_alter_historicalmouse_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='strain',
            name='jax_stock_number',
            field=models.CharField(blank=True, help_text='(if applicable) stock number at JAX', max_length=25),
        ),
        migrations.AlterField(
            model_name='historicalmouse',
            name='cage',
            field=models.ForeignKey(blank=True, db_constraint=False, help_text='the cage this mouse lives in', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='colony.cage'),
        ),
        migrations.AlterField(
            model_name='historicalmouse',
            name='sex',
            field=models.IntegerField(choices=[(0, 'M'), (1, 'F'), (2, '?')], help_text='sex of the mouse, if known'),
        ),
        migrations.AlterField(
            model_name='historicalmouse',
            name='user',
            field=models.ForeignKey(blank=True, db_constraint=False, help_text='(optional) the person who uses or has claimed this mouse', limit_choices_to={'active': True}, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='colony.person'),
        ),
        migrations.AlterField(
            model_name='mouse',
            name='cage',
            field=models.ForeignKey(blank=True, help_text='the cage this mouse lives in', null=True, on_delete=django.db.models.deletion.PROTECT, to='colony.cage'),
        ),
        migrations.AlterField(
            model_name='mouse',
            name='sex',
            field=models.IntegerField(choices=[(0, 'M'), (1, 'F'), (2, '?')], help_text='sex of the mouse, if known'),
        ),
        migrations.AlterField(
            model_name='mouse',
            name='user',
            field=models.ForeignKey(blank=True, help_text='(optional) the person who uses or has claimed this mouse', limit_choices_to={'active': True}, null=True, on_delete=django.db.models.deletion.PROTECT, to='colony.person'),
        ),
        migrations.AlterField(
            model_name='strain',
            name='name',
            field=models.CharField(help_text='name of the strain (example: CBA/J)', max_length=50, unique=True),
        ),
    ]
