# Generated by Django 4.0.4 on 2022-05-04 01:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('colony', '0041_strain_jax_stock_number_alter_historicalmouse_cage_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalmouse',
            name='notes',
            field=models.CharField(blank=True, help_text='(optional) custom notes about this mouse', max_length=200),
        ),
        migrations.AlterField(
            model_name='historicalmouse',
            name='sack_date',
            field=models.DateField(blank=True, help_text='(if applicable) the date this mouse was sacked', null=True, verbose_name='sac date'),
        ),
        migrations.AlterField(
            model_name='mouse',
            name='notes',
            field=models.CharField(blank=True, help_text='(optional) custom notes about this mouse', max_length=200),
        ),
        migrations.AlterField(
            model_name='mouse',
            name='sack_date',
            field=models.DateField(blank=True, help_text='(if applicable) the date this mouse was sacked', null=True, verbose_name='sac date'),
        ),
    ]
