# Generated by Django 4.0.4 on 2023-10-19 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('colony', '0045_cage_sticker_historicalcage_sticker'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalmouse',
            name='toe_clipped',
            field=models.CharField(blank=True, help_text='(optional) comma-separated list of clipped toe numbers', max_length=20),
        ),
        migrations.AddField(
            model_name='mouse',
            name='toe_clipped',
            field=models.CharField(blank=True, help_text='(optional) comma-separated list of clipped toe numbers', max_length=20),
        ),
    ]
